import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../models/goal.dart';
import '../providers/auth_notifier.dart';
import '../services/goal_repository.dart';

part 'goal_notifier.g.dart';

/// Streams the authenticated user's goals and exposes CRUD operations.
///
/// Uses a Firestore real-time listener so mutations from other devices are
/// reflected automatically without manual state updates.
@riverpod
class GoalNotifier extends _$GoalNotifier {
  @override
  Stream<List<Goal>> build() {
    final user = ref.watch(authNotifierProvider).valueOrNull;
    if (user == null) return Stream.value([]);
    return ref.watch(goalRepositoryProvider).watchGoals(user.uid);
  }

  /// Creates a new goal. The Firestore document ID is generated by the
  /// repository and embedded in the stored document.
  Future<void> createGoal({
    required String title,
    required double targetAmount,
    required double monthlyContribution,
    required double expectedReturnRate,
    required DateTime targetDate,
  }) async {
    final user = ref.read(authNotifierProvider).valueOrNull;
    if (user == null) throw StateError('Not authenticated');

    final repo = ref.read(goalRepositoryProvider);
    final id = repo.generateGoalId(user.uid);
    final goal = Goal(
      id: id,
      title: title,
      targetAmount: targetAmount,
      monthlyContribution: monthlyContribution,
      expectedReturnRate: expectedReturnRate,
      targetDate: targetDate,
      createdAt: DateTime.now(),
    );
    await repo.createGoal(user.uid, goal);
  }

  Future<void> updateGoal(Goal goal) async {
    final user = ref.read(authNotifierProvider).valueOrNull;
    if (user == null) throw StateError('Not authenticated');
    await ref.read(goalRepositoryProvider).updateGoal(user.uid, goal);
  }

  Future<void> deleteGoal(String goalId) async {
    final user = ref.read(authNotifierProvider).valueOrNull;
    if (user == null) throw StateError('Not authenticated');
    await ref.read(goalRepositoryProvider).deleteGoal(user.uid, goalId);
  }
}

/// Returns a single [Goal] by [goalId] from the current goals stream,
/// or null if not found.
@riverpod
Goal? goalById(Ref ref, String goalId) {
  final goals = ref.watch(goalNotifierProvider).valueOrNull ?? [];
  for (final g in goals) {
    if (g.id == goalId) return g;
  }
  return null;
}
